name: psyIndex
version: '${version}'
main: io.github.starb08.psyindex.PsyIndex
api-version: '1.20'
depend: [kotlin]
libraries:
  - io.github.monun:kommand-core:3.1.7
  - io.github.monun:invfx-core:3.3.2
